---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  glance:
    customServiceConfig: |
      [DEFAULT]
      debug=True
      enabled_backends = default_backend:swift
      [glance_store]
      default_backend = default_backend
      [default_backend]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}
      [database]
      mysql_wsrep_sync_wait = 1
    default:
      replicas: 1

  swift:
    enabled: true

  nova:
    apiServiceTemplate:
      customServiceConfig: |
        [database]
        mysql_wsrep_sync_wait = 1
        [api_database]
        mysql_wsrep_sync_wait = 1
    cellTemplates:
      cell0:
        conductorServiceTemplate:
          customServiceConfig: |
            [database]
            mysql_wsrep_sync_wait = 1
            [api_database]
            mysql_wsrep_sync_wait = 1
      cell1:
        conductorServiceTemplate:
          customServiceConfig: |
            [database]
            mysql_wsrep_sync_wait = 1
            [api_database]
            mysql_wsrep_sync_wait = 1
    schedulerServiceTemplate:
      customServiceConfig: |
        [database]
        mysql_wsrep_sync_wait = 1
        [api_database]
        mysql_wsrep_sync_wait = 1

  octavia:
    enabled: true
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    octaviaAPI:
      networkAttachments:
        - internalapi
    octaviaHousekeeping:
      networkAttachments:
        - octavia
    octaviaHealthManager:
      networkAttachments:
        - octavia
    octaviaWorker:
      networkAttachments:
        - octavia

  ovn:
    ovnController:
      nicMappings:
        datacentre: ocpbr
        octavia: octbr
